services:
  postgresql:
    container_name: postgresql_container
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/bitnami/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=challenge
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_USER_PASSWORD} # Password of user "postgres"
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
    networks:
      - batch_network

  document_management:
    build: ./..
    container_name: document_management_service_container
    ports:
      - "8080:8080"
    networks:
      - batch_network
    depends_on:
      - postgresql
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql_container:5432/challenge
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - MINIO_URL=http://host.docker.internal:9000
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

  # Include all the necessary settings to include a document management service in the stack
  # Remember to configure this service to limit the memory to 50MB
  # document-management-service:
  #    environment:
  #      - JAVA_OPTS=-Xmx50m -Xms50m
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 50M

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
